### ISSUE TITLE
Should I maintain this?

### ISSUE THREAD

**Issue by MegaphoneJon** [JMAConsulting/biz.jmaconsulting.batchthresholdbundling#5]
Hi Joe,

I see my 2018 PRs are unmerged; I know at the time you had a client using this, but my guess is that you don't.  If you don't have a need for this anymore I won't submit further PRs; I've made a small number of fixes.

**Comment by JoeMurray** [comment]
@monishdeb didn't get around to one. The other had a response suggesting the functionality would be better moved to a different  extension, and I didn't see a response to that one. I'd be willing to merge now if it is still relevant.

**Comment by MegaphoneJon** [comment]
OK, good to know.  I'll try to find some time to review my various fixes and put them into separate PRs.
